### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by SamWhited** [siacs/HttpUploadComponent#21]
Currently a user can send as many upload requests as they want to the component. Since all files are stored in a global dict, this can cause memory usage to grow in an unbounded way. Having some sort of rate limit and TTL for slots would solve this problem.

Modifying the whitelist to look something like this might solve the problem:

```yaml
whitelist:
  - name: yourdomain.tld
    rate_limit: 1/60 # requests per second
    slot_ttl: 60 # seconds
  - name: someotherdomain.tld
```

but would make checking of things in the whitelist harder. Alternatively, a global `rate_limit` and `ttl` is probably fine for 90% of cases to keep the reference implementation simple.

I started to do this, but wasn't sure what the prefered format would be. Thoughts?
